// Mark Wu 2024

// libraries
#include <Arduino.h>
#include <U8g2lib.h> // referenced from Seeed studio: https://wiki.seeedstudio.com/Grove-OLED-Display-0.96-SSD1315/
#include <Wire.h>

// files
#include "images.h"

// Define pinouts from the electrical schematic - these were actually generated by Flux Copilot! https://flux.ai/markwuflux/lethal-company-pro-flashlight-power-board-v1?fit=93ab962e-d0c2-4aef-a98e-da0d52874cf4
#define I2C_SDA D4 
#define I2C_SCL D5 
// Other defines
#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels

// global variables

U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* clock=*/ I2C_SCL, /* data=*/ I2C_SDA, /* reset=*/ U8X8_PIN_NONE);  // High speed I2C

void setup() {
  //setup pinouts from Macro definitions
  u8g2.begin();

}

void loop() {
  u8g2.clearBuffer();                   // clear the internal memory
  u8g2.drawXBM( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, fullBatterySSD1315); // draw the full battery bitmap to the display Reference: https://github.com/olikraus/u8g2/wiki/u8g2reference#drawxbm
  u8g2.sendBuffer();                    // transfer internal memory to the display
  delay(1000);  
  

}
