// Mark Wu 2024

// libraries
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

// files
#include "images.h"

// Define pinouts from the electrical schematic - these were actually generated by Flux Copilot! https://flux.ai/markwuflux/lethal-company-pro-flashlight-power-board-v1?fit=93ab962e-d0c2-4aef-a98e-da0d52874cf4
#define I2C_SDA D4 
#define I2C_SCL D5 
// Other defines
#define SCREEN_WIDTH 128 // OLED display width, in pixels Reference: https://mischianti.org/images-to-byte-array-online-converter-cpp-arduino/
#define SCREEN_HEIGHT 64 // OLED display height, in pixels

// global variables and objects

//// Declaration for an SSD1306 display connected to I2C (SDA, SCL pins)
#define OLED_RESET     -1 // Reset pin # (or -1 if sharing Arduino reset pin)
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);


void setup() {
  //setup pinouts from Macro definitions
  if(!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
    Serial.println(F("SSD1306 allocation failed"));
    for(;;); // Don't proceed, loop forever
  }
  display.clearDisplay();
  display.drawBitmap(0, 0, fullBattery, SCREEN_WIDTH, SCREEN_HEIGHT, WHITE);
  display.display();
  delay(5000);

}

void loop() {
  display.clearDisplay();
  display.drawBitmap(0, 0, fullBattery, SCREEN_WIDTH, SCREEN_HEIGHT, WHITE);
  // display.drawBitmap(0, 0, monkeyAnimation[count], 64, 128, WHITE); // for later
  display.display();
  delay(1000);  
  

}
