// Mark Wu 2024

// Define pinouts from the electrical schematic - these were actually generated by Flux Copilot! https://flux.ai/markwuflux/lethal-company-pro-flashlight-power-board-v1?fit=93ab962e-d0c2-4aef-a98e-da0d52874cf4
#define I2S_BCLK D1 
#define I2S_DIN D0 
#define I2S_LRCLK D2 
#define LED_CC_2_5A_PG D9 
#define LED_CC_2_5A_EN D10 
#define I2C_SDA D4 
#define I2C_SCL D5 
#define VBATT_MON_10_43 D3 
#define _3_3V_BUCK_BOOST_PG D8
#define SW_DIGITAL D6 
#define _5V_MON_50_33 D7  

// global variables
int buttonState = 0;

void setup() {
  Serial.begin(115200);
  Serial.println("Starting Up");
  //setup pinouts from Macro definitions
  pinMode(LED_CC_2_5A_EN, OUTPUT);
  // digitalWrite(LED_CC_2_5A_EN, 0); // disabling the LED output right now because it's not working due to short circuit protection logic
  // at first, just test the toggling of the CC converter. Perform some tests under load
  digitalWrite(LED_CC_2_5A_EN, 1);
  pinMode(SW_DIGITAL, INPUT);

}

void loop() {
  Serial.println("beep");
  delay(1000);
  

}
